dist: xenial
language: cpp
sudo: false

jobs:
  include:
    - os: linux
      env: LLVM_VERSION=7.0.1
      compiler: gcc
    - os: linux
      env: LLVM_VERSION=7.0.1
      compiler: gcc
      arch: s390x
    - os: linux
      env: LLVM_VERSION=8.0.1
      compiler: clang
    - os: osx
      osx_image: xcode9.4
      env: LLVM_VERSION=7.0.0
    - os: osx
      osx_image: xcode10.1
      env: LLVM_VERSION=7.0.0
    - os: windows
      env: LLVM_VERSION=7.0.1
  allow_failures:
    - os: windows

cache:
  directories:
    - llvm-8.0.1
    - llvm-7.0.1
    - llvm-7.0.0

addons:
  apt:
    packages:
    - ninja-build

before_install:
  # Should be part of addons
  - |
    if [ "${TRAVIS_OS_NAME}" = "windows" ]; then
      choco install ninja python
      export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
      ./scripts/vcenv.bat | sed -e 's/\\/\//g' -e 's/C:/\/c/g' -e 's/;/:/g' > /tmp/vcenv.sh
      source /tmp/vcenv.sh
      export CC=cl.exe
      export CXX=cl.exe
    fi
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      wget -O ninja-mac.zip https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-mac.zip
      mkdir ninja
      tar -xf ninja-mac.zip -C ninja
      rm ninja-mac.zip
      export PATH="$PWD/ninja:$PATH"
    fi
    if [ ${TRAVIS_CPU_ARCH} = "s390x" ]; then
      apt install clang-7
      apt install clang-8
      apt install clang-9
    fi

install:
  - |
    export LLVM_ROOT_DIR="$PWD/llvm-$LLVM_VERSION"
    if  [ "${TRAVIS_OS_NAME}" = "windows" ]; then
      if [ ! -e "$LLVM_ROOT_DIR/bin/llvm-config.exe" ]; then
        wget -O llvm.7z https://github.com/ldc-developers/llvm/releases/download/ldc-v$LLVM_VERSION/llvm-$LLVM_VERSION-windows-x86-withAsserts-clang.7z
        mkdir -p $LLVM_ROOT_DIR
        7z x llvm.7z -o$LLVM_ROOT_DIR
        rm llvm.7z
      fi
    elif [ ${TRAVIS_CPU_ARCH} -ne "s390x" ]; then
      if [ ! -e "$LLVM_ROOT_DIR/bin/llvm-config" ]; then
        if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
          if [ "${LLVM_VERSION}" = "4.0.1" ]; then
            export LLVM_ARCH="x86_64-linux-gnu-debian8"
          else
            export LLVM_ARCH="x86_64-linux-gnu-ubuntu-16.04"
          fi
        else
          export LLVM_ARCH="x86_64-apple-darwin"
        fi
        wget -O llvm.tar.xz http://releases.llvm.org/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-${LLVM_ARCH}.tar.xz
        mkdir -p $LLVM_ROOT_DIR
        tar -xf llvm.tar.* --strip 1 -C $LLVM_ROOT_DIR
        rm llvm.tar.*
      fi
    fi
  - export LLVM_CMAKE_DIR="$($LLVM_ROOT_DIR/bin/llvm-config --cmakedir)"
  - pip install --user lit
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ld --version; fi
  - cmake --version
  - ninja --version
  - python --version
  - python -c "import lit; lit.main();" --version | head -n 1

script:
  # Invoke CMake to generate the Ninja build files.
  - export SRC_DIR="$PWD"
  - mkdir ../build && cd ../build
  - cmake -G Ninja -DCMAKE_INSTALL_PREFIX=$LLVM_CMAKE_DIR ${SRC_DIR}
  - ninja -j3
